name: SAST - Static Application Security Testing

on:
  push:
    branches: [main]
  pull_request:

jobs:
  sast:
    name: Static Code Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install bandit semgrep

      - name: Run Bandit (Python SAST)
        run: bandit -r . -f json -o bandit-report.json

      - name: Run Semgrep (Custom or Predefined Rules)
        run: semgrep --config p/ci --json > semgrep-report.json

      - name: Upload Bandit Report
        uses: actions/upload-artifact@v4
        with:
          name: bandit-report
          path: bandit-report.json

      - name: Upload Semgrep Report
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-report
          path: semgrep-report.json
