name: CRDA Dependency Scan

on:
  workflow_dispatch:

jobs:
  sca:
    name: SCA (CRDA) Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requerimientos.txt

      - name: Install SCA tool (CRDA)
        uses: redhat-actions/crda@v1.2
        id: crda_scan
        with:
          manifest_file: requerimientos.txt
          snyk_token: ${{ secrets.CUR_SNYK_KEY }}
          fail_on: never

      - name: Print JSON analysis report
        run: cat ${{ steps.crda_scan.outputs.crda_report_json }}

      - name: Print SARIF analysis report
        run: cat ${{ steps.crda_scan.outputs.crda_report_sarif }}

      - name: Print report link
        run: echo ${{ steps.crda_scan.outputs.report_link }}
