name: SCA - pip-audit Dependency Scan

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  sca:
    name: Static Composition Analysis (pip-audit)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install SCA tool (pip-audit)
        run: pip install pip-audit

      - name: Run pip-audit scan
        run: pip-audit --output-format json > audit-report.json

      - name: Print JSON analysis report
        run: cat audit-report.json

      - name: Upload pip-audit report
        uses: actions/upload-artifact@v4
        with:
          name: pip-audit-report
          path: audit-report.json
