name: SCA - Software Composition Analysis

on:
  push:
    branches: [master]
  pull_request:

jobs:
  sca:
    name: Dependency Vulnerability Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install pip-audit
        run: |
          python -m pip install --upgrade pip
          pip install pip-audit

      - name: Audit dependencies
        run: pip-audit -r requirements.txt -f json -o audit-report.json

      - name: Upload Audit Report
        uses: actions/upload-artifact@v4
        with:
          name: pip-audit-report
          path: audit-report.json
